### ISSUE TITLE
Step 7 won't complete

### ISSUE THREAD

**Issue by a-a-ron** [githubtraining/security-strategy-essentials#3]
Hey @hectorsector, I could use some 👀 on this step: https://github.com/githubtraining/security-strategy-essentials/blob/master/config.yml#L187-L206

It responds with the correct bot responses when the learner pushes up the content but the step itself don't move onto the next step. 

Thoughts on why it's doing that?

**Comment by hectorsector** [comment]
@a-a-ron it looks like the responses are just flipped
https://github.com/githubtraining/security-strategy-essentials/blob/3b450ada1b544d98bf7cf1c9b5f2fa4fd3d96039/config.yml#L202-L206

I think you want 
```yaml
      else:
      - type: respond
        with: 07_error-file-change.md #failed response to remove .env file
    - type: respond
      with: 07_success-file-change.md #success response to remove .env file | Add note about contacting support for garbage collection
```

This may have been confusing because you'd be seeing an error response when in fact the step was completed. In my own testing it seems to have worked.
